cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - cache/Cypress
    - node_modules/
    - package-lock.json

image: cypress/base:10

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md



stages:
 - build
 - fresh_build
 - test


build-job:
  stage:
    build
  script:
    - npm ci
    - npm run e2e:verify 

build-job-from-bottom-if-no-cache:
  stage:
    fresh_build
  script:
    - npm install
    - npm run e2e:verify
  when:
    on_failure



unittest-job:
  stage:
    test
  script:
    npm test
    

integrationtest-job:
  stage:
    test
  script: 
    # start the server in the background
    - npm start --silent &
    # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run e2e --record
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
 
