image: cypress/base:10

variables:
  npm_config_cache: "$CI_PROJECT_DIR/projectum-quattuor/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/projectum-quattuor/cache/Cypress"

stages:
  - build
  - test

before_script:
  # change directory to the React project
  - cd projectum-quattuor

build-job:
  stage: build
  script:
   - npm ci || npm install
   - npm run e2e:verify


unittest-job:
  stage: test
  script:
    # if cache is not present on this runner, install everything
    - (npm ci && npm test) || (npm install --only=prod && npm test)

  integrationtest-job:
  stage: test
  script:
  # run Cypress test in load balancing mode, pass id to tie jobs together
    - (npm ci && npm run e2e --record) || (npm install && npm run e2e --record)
# Keep videoes & screenshots for four days for debugging over weekend if needed
  artifacts:
    expire_in: 4 days
    when: always
    paths:
    - projectum-quattuor/cypress/screenshots
    - projectum-quattuor/cypress/videos

