# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
# Note that cache is per-runner
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
  - projectum-quattuor/.npm/
  - projectum-quattuor/cache/Cypress
  - projectum-quattuor/node_modules/
  - projectum-quattuor/package-lock.json

image: cypress/base:10

variables:
  npm_config_cache: "$CI_PROJECT_DIR/projectum-quattuor/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/projectum-quattuor/cache/Cypress"

stages:
  - build
  - test
  - test-e2e

before_script:
  # change directory to the React project
  - cd projectum-quattuor

build-job:
  stage: build
  script:
    # If cache is present on this runner, use npm ci as it is faster and does not reinstall Cypress
    - npm ci || npm install
    - npm run e2e:verify

unittest-job:
  stage: test
  script:
    # if cache is not present on this runner, install everything
    - npm test || npm install && npm test

  when: always
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - projectum-quattuor/.npm/
      - projectum-quattuor/cache/Cypress
      - projectum-quattuor/node_modules/
      - projectum-quattuor/package-lock.json
    policy: pull

integrationtest-job:
  stage: test-e2e
  script:
  # start the server in the background
    - npm start --silent &
  # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run e2e --record || npm install && npm start --silent && npm run e2e --record
  when: always
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - projectum-quattuor/.npm/
      - projectum-quattuor/cache/Cypress
      - projectum-quattuor/node_modules/
      - projectum-quattuor/package-lock.json
    policy: pull
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - projectum-quattuor/cypress/screenshots
    - projectum-quattuor/cypress/videos

